import type { Config } from 'tailwindcss'
import tailwindcssAnimate from 'tailwindcss-animate'

const config: Config = {
  darkMode: ['class'],
  content: [
    './pages/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './app/**/*.{ts,tsx}',
    './src/**/*.{ts,tsx}',
    './lib/**/*.{ts,tsx}',
    './utils/**/*.{ts,tsx}',
    './hooks/**/*.{ts,tsx}',
    './providers/**/*.{ts,tsx}',
    './contexts/**/*.{ts,tsx}',
    './types/**/*.{ts,tsx}',
  ],
  prefix: '',
  // Safelist para classes dinâmicas que não devem ser removidas no build
  safelist: [
    // Cores personalizadas do projeto
    'text-[#1E1D40]',
    'text-[#4AB0D9]',
    'text-[#D90D32]',
    'text-[#F2E6D8]',
    'bg-[#1E1D40]',
    'bg-[#4AB0D9]',
    'bg-[#D90D32]',
    'bg-[#F2E6D8]',
    'border-[#1E1D40]',
    'border-[#4AB0D9]',
    'border-[#D90D32]',
    'border-[#F2E6D8]',
    'hover:bg-[#4AB0D9]',
    'hover:bg-[#3989ac]',
    'hover:text-[#4AB0D9]',
    'hover:text-[#1E1D40]',
    'hover:border-[#4AB0D9]',
    'focus:border-[#4AB0D9]',
    // Variações de opacidade
    'text-[#1E1D40]/70',
    'text-[#1E1D40]/80',
    'text-[#1E1D40]/60',
    'bg-[#4AB0D9]/10',
    'bg-[#4AB0D9]/5',
    'bg-[#4AB0D9]/20',
    'bg-[#4AB0D9]/30',
    'bg-[#4AB0D9]/90',
    'border-[#4AB0D9]/20',
    'hover:bg-[#D90D32]/90',
    // Classes de gradiente dinâmicas
    {
      pattern: /bg-gradient-to-br/,
    },
    {
      pattern: /from-(blue|green|purple|red|yellow|indigo|pink|gray)-500/,
    },
    {
      pattern: /to-(blue|green|purple|red|yellow|indigo|pink|gray)-600/,
    },
    // Classes de validação
    'text-red-500',
    'text-green-500',
    'text-green-600',
    'text-gray-500',
    'text-blue-500',
    'text-yellow-500',
    'bg-green-500',
    'bg-red-500',
    'bg-gray-300',
    // Classes de status
    'text-green-600',
    'text-red-600',
    'text-yellow-600',
    'text-blue-600',
    // Classes de tamanho dinâmico
    'w-8',
    'h-8',
    'w-10',
    'h-10',
    'w-12',
    'h-12',
    'w-16',
    'h-16',
    // Classes de posicionamento
    'aspect-[16/5]',
    'aspect-square',
    'w-32',
    'h-32',
    'w-48',
    'w-80',
    // Classes de texto dinâmico
    'text-xs',
    'text-sm',
    'text-base',
    'text-lg',
    'text-xl',
    'text-2xl',
    'text-3xl',
    'text-4xl',
    'text-5xl',
    // Classes de espaçamento
    'ml-6',
    'mb-4',
    'mt-6',
    'p-4',
    'p-6',
    'px-2',
    'py-1',
    'px-4',
    'py-2',
    'px-6',
    'py-3',
    // Classes de borda
    'rounded-full',
    'rounded-lg',
    'rounded-xl',
    'border-2',
    'border-dashed',
    // Classes de flexbox
    'flex-1',
    'flex-shrink-0',
    'justify-end',
    'justify-start',
    'order-first',
    // Classes de grid
    'max-w-[70%]',
    // Classes de transformação
    'scale-105',
    'group-hover:scale-105',
    'hover:scale-105',
    // Classes de transição
    'transition-all',
    'transition-colors',
    'transition-transform',
    'duration-200',
    'duration-300',
    'ease-in-out',
    // Classes de sombra
    'shadow-lg',
    'shadow-xl',
    'hover:shadow-xl',
    'shadow-md',
    'shadow-2xl',
    // Classes de overflow
    'overflow-hidden',
    'line-clamp-3',
    'truncate',
    // Classes de backdrop
    'backdrop-blur-sm',
    'bg-white/80',
    // Classes de animação
    'animate-spin',
    'group-hover:text-[#4AB0D9]',
    // Classes condicionais específicas
    'capitalize',
    'fill-yellow-400',
    'text-yellow-400',
    'text-gray-300',
    'relative',
    'absolute',
    'fixed',
    'top-0',
    'right-0',
    'left-0',
    'bottom-0',
    'z-50',
    'z-70',
    'transform',
    'cursor-pointer',
    'disabled:opacity-50',
    'disabled:cursor-not-allowed',
    'focus:outline-none',
    'focus:ring-0',
    'hover:bg-gray-50',
    'hover:bg-gray-100',
    'border-gray-200',
    'border-gray-300',
    'text-gray-600',
    'text-gray-700',
    'bg-gray-50',
    'bg-gray-100',
  ],
  theme: {
    screens: {
      sm: '640px',
      md: '641px',
      lg: '1025px',
      xl: '1280px',
      '2xl': '1536px',
    },
    container: {
      center: true,
      padding: '2rem',
      screens: {
        '2xl': '1400px',
      },
    },
    extend: {
      colors: {
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      keyframes: {
        'accordion-down': {
          from: { height: '0' },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: '0' },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
      },
    },
  },
  plugins: [tailwindcssAnimate],
}

export default config
